# .github/workflows/hello-world.yml
name: Hello World Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies from requirements.txt
        pip install -r requirements.txt
        # Alternatively, install logcliasst directly
        # pip install logcliasst

    - name: Run Hello World script
      run: |
        python client_conf.py
